export interface RealtimeEvent {
  eventId: string;
  type: string;
  timestamp: string;
  workspaceId?: string;
  projectId?: string;
  resourceId?: string;
  actorId?: string;
  payload?: Record<string, unknown>;
}

export const REALTIME_EVENT_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
  USER_AWAY: 'USER_AWAY',
  TYPING_STARTED: 'TYPING_STARTED',
  TYPING_STOPPED: 'TYPING_STOPPED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  WORKSPACE_MEMBER_ADDED: 'WORKSPACE_MEMBER_ADDED',
  WORKSPACE_MEMBER_REMOVED: 'WORKSPACE_MEMBER_REMOVED',
  PROJECT_UPDATED: 'PROJECT_UPDATED'
} as const;
